import React from 'react';
import { FileText, Cpu, Database, Shield, Layout, Settings } from "lucide-react";
import { motion } from "framer-motion";

export default function SRS() {
  return (
    <div style={{ padding: 40, flex: 1, overflowY: 'auto' }}>
      <div style={{ marginBottom: 40, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 style={{ fontSize: 32, fontWeight: 800, margin: 0 }}>Auto-Generated SRS</h1>
          <p style={{ color: 'var(--text-muted)', fontSize: 15, marginTop: 4 }}>Software Requirements Specification dynamically generated by NexaVault AI.</p>
        </div>
        <div style={{ background: 'rgba(16, 185, 129, 0.1)', color: 'var(--success)', padding: '6px 16px', borderRadius: 20, fontSize: 13, fontWeight: 800 }}>
          VERSION 2.4.1 (APPROVED)
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'minmax(500px, 2fr) 1fr', gap: 32 }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
          
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="card" style={{ padding: 32, background: 'var(--bg-card)', borderRadius: 20 }}>
            <h2 style={{ fontSize: 20, margin: '0 0 16px 0', display: 'flex', alignItems: 'center', gap: 12 }}>
              <FileText color="var(--primary)" /> 1. Project Overview
            </h2>
            <p style={{ color: 'var(--text-secondary)', lineHeight: 1.6, fontSize: 14 }}>
              DataCopilot is a cutting-edge AI-driven analytics dashboard designed for startup ecosystems. It ingests CSV data, 
              processes machine learning aggregations (such as churn prediction and budget forecasting), and generates 
              conversational insights through Google Gemini's underlying API infrastructure.
            </p>
          </motion.div>

          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="card" style={{ padding: 32, background: 'var(--bg-card)', borderRadius: 20 }}>
            <h2 style={{ fontSize: 20, margin: '0 0 20px 0', display: 'flex', alignItems: 'center', gap: 12 }}>
              <Layout color="#f59e0b" /> 2. Functional Requirements
            </h2>
            <ul style={{ color: 'var(--text-secondary)', lineHeight: 1.8, fontSize: 14, paddingLeft: 20, margin: 0 }}>
              <li><strong>FR-01:</strong> The system must allow users to upload datasets (.csv formats) up to 50MB.</li>
              <li><strong>FR-02:</strong> Dynamic rendering of numerical parameters and dataset heuristics upon upload.</li>
              <li><strong>FR-03:</strong> Natural Language Processing (NLP) querying interface for users to extract insights without writing SQL.</li>
              <li><strong>FR-04:</strong> Interactive project board synchronizing with the central MongoDB instance.</li>
              <li><strong>FR-05:</strong> Scheduled and manual synthesis reporting generation using ML metrics.</li>
            </ul>
          </motion.div>

          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="card" style={{ padding: 32, background: 'var(--bg-card)', borderRadius: 20 }}>
            <h2 style={{ fontSize: 20, margin: '0 0 20px 0', display: 'flex', alignItems: 'center', gap: 12 }}>
              <Database color="#10b981" /> 3. System Architecture
            </h2>
            <p style={{ color: 'var(--text-secondary)', lineHeight: 1.6, fontSize: 14, marginBottom: 16 }}>
              The architecture follows a standard decoupled Client-Server model relying heavily on asynchronous data streaming.
            </p>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
               <div style={{ background: 'rgba(255,255,255,0.03)', padding: 16, borderRadius: 12, border: '1px solid var(--border)' }}>
                 <div style={{ fontSize: 12, fontWeight: 800, color: 'var(--text-muted)', marginBottom: 8 }}>FRONTEND (CLIENT)</div>
                 <div style={{ fontSize: 14, fontWeight: 700 }}>React 18 + Vite</div>
                 <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>Framer Motion, Lucide Icons, Axios</div>
               </div>
               <div style={{ background: 'rgba(255,255,255,0.03)', padding: 16, borderRadius: 12, border: '1px solid var(--border)' }}>
                 <div style={{ fontSize: 12, fontWeight: 800, color: 'var(--text-muted)', marginBottom: 8 }}>BACKEND (SERVER)</div>
                 <div style={{ fontSize: 14, fontWeight: 700 }}>FastAPI + Python 3</div>
                 <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>Motor (Async MongoDB), Google GenAI</div>
               </div>
            </div>
          </motion.div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
          <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="card" style={{ padding: 32, background: 'linear-gradient(135deg, var(--primary)11, var(--bg-card))', border: '1px solid var(--primary)33', borderRadius: 20 }}>
             <h3 style={{ margin: '0 0 16px 0', fontSize: 16, display: 'flex', alignItems: 'center', gap: 8 }}>
               <Shield size={18} color="var(--primary)" /> Non-Functional Reqs
             </h3>
             <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
               <div style={{ fontSize: 13, color: 'var(--text-secondary)' }}><strong>Latency:</strong> API responses &lt; 200ms</div>
               <div style={{ fontSize: 13, color: 'var(--text-secondary)' }}><strong>Security:</strong> SHA-256 Auth Hashing</div>
               <div style={{ fontSize: 13, color: 'var(--text-secondary)' }}><strong>Availability:</strong> 99.9% Uptime</div>
               <div style={{ fontSize: 13, color: 'var(--text-secondary)' }}><strong>Scalability:</strong> Horizontal via Docker</div>
             </div>
          </motion.div>

          <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: 0.1 }} className="card" style={{ padding: 32, background: 'var(--bg-card)', borderRadius: 20 }}>
             <h3 style={{ margin: '0 0 16px 0', fontSize: 16, display: 'flex', alignItems: 'center', gap: 8 }}>
               <Cpu size={18} color="var(--text-muted)" /> Compliance & Details
             </h3>
             <ul style={{ color: 'var(--text-secondary)', fontSize: 13, paddingLeft: 16, margin: 0, lineHeight: 1.6, display: 'flex', flexDirection: 'column', gap: 8 }}>
                <li>GDPR Compliant Data Storage</li>
                <li>SOC-2 Type II Certified Host</li>
                <li>Automated daily backups to AWS S3</li>
             </ul>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
